### ISSUE TITLE
release 0.11 (including publishing it for Scala 2.13.0-M3)

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#126]
once ScalaTest is available we should be good to go

**Comment by raboof** [comment]
So waiting for https://github.com/scalatest/scalatest/issues/1321 for now 👍

**Comment by patriknw** [comment]
we also need to publish com.typesafe#ssl-config-core_2.13.0-M3;0.2.2

**Comment by SethTisue** [comment]
@patriknw for https://github.com/akka/akka/issues/24507, you mean?

**Comment by patriknw** [comment]
yes, commented at wrong place, thanks

**Comment by SethTisue** [comment]
@raboof I tagged v0.11 and tried to `+publishSigned`, but `java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.11.0/0.11/genjavadoc-plugin_2.11.0-0.11-sources.jar.asc was refused by the server: Unauthorized`

I think I simply don't have the needed rights. I know I have Scala rights on Sonatype, but I probably don't have Typesafe/Lightbend rights. (When I've published Lightbend stuff before it was through Bintray, I think.)

can you either grant them me the rights, or just go ahead and publish v0.11 yourself, either way?

**Comment by ktoso** [comment]
I think I may have "the power"

**Comment by ktoso** [comment]
I'll try

**Comment by SethTisue** [comment]
you are the ship-it squirrel, are you not?

**Comment by ktoso** [comment]
:shipit: 

<img width="20" alt="slack_-_lightbend_cafe" src="https://user-images.githubusercontent.com/120979/36294052-56b71460-1321-11e8-9fdd-0a5ad9b88e07.png">

**Comment by ktoso** [comment]
![nexus_repository_manager](https://user-images.githubusercontent.com/120979/36294766-3df256ba-1326-11e8-8a02-f8eed81b151b.png)
Quite some stuff there.

Releasing 0.11

**Comment by raboof** [comment]
👍 and let's #128 at some point ;)

**Comment by SethTisue** [comment]
thanks Konrad!
