### ISSUE TITLE
publish for Scala 2.12.6

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#138]
@ktoso could you take this...? judging from https://github.com/lightbend/genjavadoc/pull/132#issuecomment-375138554 you'll be allllll over this

**Comment by SethTisue** [comment]
I'll take care of it

**Comment by SethTisue** [comment]
see also #128

**Comment by 2m** [comment]
Yea, I can do a quick release.

**Comment by 2m** [comment]
`genjavadoc-plugin_2.12.6-0.11` is on its way to Maven Central.
