### ISSUE TITLE
publish for Scala 2.13.0-M5

### ISSUE THREAD

**Issue by xuwei-k** [lightbend/genjavadoc#144]

**Comment by SethTisue** [comment]
* [ ] https://github.com/scalatest/scalatest/issues/1409

**Comment by SethTisue** [comment]
(it would be nice to get rid of the ScalaTest dependency and just use JUnit; that's https://github.com/lightbend/genjavadoc/issues/109)

**Comment by SethTisue** [comment]
https://github.com/lightbend/genjavadoc/pull/145 removes the dependency on ScalaTest

@raboof @dwijnand @2m who wants to pull the publishing levers this time?

**Comment by SethTisue** [comment]
@raboof @dwijnand @2m who wants to pull the publishing levers this time?

**Comment by SethTisue** [comment]
oh there needs to be a PR bumping the Scala dependency first. I'll do that part, working on it now

**Comment by 2m** [comment]
I can pull some levers when levers are needed to be pulled.

**Comment by SethTisue** [comment]
#146 is merged, so... Martynas, pull those levers!

note that we don't need a version number bump, there are no user-visible changes since https://github.com/lightbend/genjavadoc/tree/v0.11_2.13.0-M4:

```
% git hist @ ^v0.11_2.13.0-M4
*   a7587f2 - (HEAD -> master, origin/master, origin/HEAD) Merge pull request #146 from SethTisue/support-m5 (13 seconds ago) <Seth Tisue>
|\  
| * a9729d3 - (SethTisue/support-m5, support-m5) support Scala 2.13.0-M5 (drop M4 support) (21 minutes ago) <Seth Tisue>
|/  
* 7fca8d7 - Merge pull request #145 from dwijnand/junit (3 hours ago) <Seth Tisue>
* 92de414 - Remove ScalaTest (6 hours ago) <Dale Wijnand>
* c65b597 - Port CompilerSpec/BasicSpec/StrictVisibilitySpec to JUnit (6 hours ago) <Dale Wijnand>
* 3676e41 - Port SignatureSpec to JUnit (6 hours ago) <Dale Wijnand>
* d5b3cc7 - Add JUnit (6 hours ago) <Dale Wijnand>
```

**Comment by 2m** [comment]
Artifacts are on their way to Maven Central!

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0-M5/0.11/ 👍

scala/make-release-notes@59fb2032679bd9fe2c89b3ec9a6dbb60d64f577e
