### ISSUE TITLE
Publish for Scala 2.12.7

### ISSUE THREAD

**Issue by raboof** [lightbend/genjavadoc#148]

**Comment by SethTisue** [comment]
who will pull the release levers? (@2m did it last time)

**Comment by 2m** [comment]
Can do it!

**Comment by 2m** [comment]
On its way to Maven Central.

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.7/0.11/
