### ISSUE TITLE
genjavadoc for 2.12.8

### ISSUE THREAD

**Issue by hepin1989** [lightbend/genjavadoc#152]
refs:https://github.com/akka/akka/pull/26039

**Comment by raboof** [comment]
should be on its way to maven central now

**Comment by SethTisue** [comment]
https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0-M5/0.11/

**Comment by SethTisue** [comment]
@raboof 2.12.9 time :-)

**Comment by SethTisue** [comment]
oh, https://github.com/lightbend/genjavadoc/issues/190 :+1:
