### ISSUE TITLE
publish for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#168]
~~but first we need to get #164 over the finish line~~ done!

**Comment by SethTisue** [comment]
@2m would you mind pulling the release levers?

**Comment by 2m** [comment]
`0.13` artifacts for `2.13.0-RC1` are on their way to Maven Central. Released from the current master and pushed the following tag to note it: https://github.com/lightbend/genjavadoc/tree/v0.13_2.13.0-RC1

**Comment by 2m** [comment]
And its [live](http://central.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0-RC1/0.13/).
