### ISSUE TITLE
publish for Scala 2.13.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#175]
like #172 

(@2m? @raboof?)

**Comment by lrytz** [comment]
I cant, releases are built locally (https://github.com/lightbend/genjavadoc/issues/128)

**Comment by lrytz** [comment]
(ah i was not actually cc'd above, i guess i'm trying to feel more important 😂)

**Comment by 2m** [comment]
Publishing

**Comment by 2m** [comment]
On its way to Maven Central from https://github.com/lightbend/genjavadoc/tree/v0.13_2.13.0-RC3

**Comment by SethTisue** [comment]
* https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0-RC3/0.13/
* d3b3725ee64d83d42f18a3170361a5a919481616

thanks @2m!
