### ISSUE TITLE
publish for Scala 2.13

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#178]
@2m are you available for this?

**Comment by 2m** [comment]
Yes. Will publish in an hour.

**Comment by 2m** [comment]
On its way to Maven Central from https://github.com/lightbend/genjavadoc/tree/v0.13_2.13.0

**Comment by SethTisue** [comment]
keeping an eye on https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13/0.13/

**Comment by patriknw** [comment]
Thanks @2m

**Comment by SethTisue** [comment]
am I looking in the wrong place, or did something go wrong, or is Sonatype being extraordinarily slow?

**Comment by SethTisue** [comment]
I'm looking in the wrong place. genjavadoc is published by compiler minor version: https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.13.0/0.13/
