### ISSUE TITLE
Problems when running with -Yrangepos

### ISSUE THREAD

**Issue by raboof** [lightbend/genjavadoc#220]
It seems that when compiling with `-Yrangepos` comments are no longer correctly associated with the right elements. Tested with `akka-cluster-typed/src/main/scala/akka/cluster/ddata/typed/javadsl/Replicator.scala` in Akka.

For now perhaps we should throw an error when `-Yrangepos` is enabled? Though that's only a temporary solution since [rangepos might be enabled by default in the future](https://github.com/scala/scala-dev/issues/472)

**Comment by marcospereira** [comment]
See some additional conversation here: https://github.com/lightbend/genjavadoc/issues/264.

> Though that's only a temporary solution since [rangepos might be enabled by default in the future](https://github.com/scala/scala-dev/issues/472)

Alright, `rangepos` is now the default. :-)
