### ISSUE TITLE
Release for Scala 2.12.14

### ISSUE THREAD

**Issue by dongjoon-hyun** [lightbend/genjavadoc#282]

**Comment by dongjoon-hyun** [comment]
Hi, @SethTisue .
I saw the repo is ready for 2.12.15 nightly, but I cannot find an artifact for 2.12.14. Could you publish it?
- https://repo1.maven.org/maven2/com/typesafe/genjavadoc/

**Comment by SethTisue** [comment]
@raboof ?

**Comment by raboof** [comment]
On its way to central!

**Comment by dongjoon-hyun** [comment]
Thank you, @raboof and @SethTisue !
