### ISSUE TITLE
Publish for Scala 2.12.16, please

### ISSUE THREAD

**Issue by SethTisue** [lightbend/genjavadoc#312]
as per https://contributors.scala-lang.org/t/scala-2-12-16-release-planning/5692/8

**Comment by SethTisue** [comment]
@raboof could you review/merge https://github.com/lightbend/genjavadoc/pull/313 and then publish...?

**Comment by raboof** [comment]
get it while it's hot at https://repo1.maven.org/maven2/com/typesafe/genjavadoc/genjavadoc-plugin_2.12.16/0.18/
